version: '3.8'

services:
    ### BACKEND ###
    unsplash-api:
        container_name: unsplash-api
        image: alvidir/unsplash-api:0.1.1
        restart: always
        ports:
            - "3001:3001"
        networks: 
            - backend

    ### ENVOY PROXY ###
    envoy:
        container_name: unsplash-api-envoy
        image: unsplash-api/envoy:0.1.1
        restart: always
        depends_on:
            - unsplash-api
        ports:
            - "8080:8080"
            - "9901:9901"
        networks: 
            - backend
            
networks:
    backend:
        name: backend
        driver: bridge