version: '3.8'

services:
    ### ENVOY PROXY ###
    #envoy:
    #    container_name: unsplash-api-envoy
    #    image: alvidir/unsplash-api:envoy
    #    restart: always
    #    ports:
    #        - "8080:8080"
    #        - "9901:9901"
    #    networks: 
    #        - backend

    ### BACKEND ###
    unsplash-api:
        container_name: unsplash-api
        image: alvidir/unsplash-api:0.1.1
        restart: always
        ports:
            - "3001:3001"
        networks: 
            - backend
        environment: 
            REST_SERVICE_PORT: 3030
            PROTO_SERVICE_PORT: 9090
            
networks:
    backend:
        name: backend
        driver: bridge